<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TracksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tracks')->delete();
        
        \DB::table('tracks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'spotify_id' => '1APBezalkm6Ow6V8e3mLVd',
            'name' => 'Darkside (Switching Vocals)',
                'album_id' => 1,
                'duration_ms' => 162485,
                'explicit' => 0,
                'popularity' => 41,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1APBezalkm6Ow6V8e3mLVd',
                'created_at' => '2025-10-24 21:48:00',
                'updated_at' => '2025-10-24 21:51:16',
            ),
            1 => 
            array (
                'id' => 2,
                'spotify_id' => '1S7KYubk2rQ9d1aydXT9Cd',
            'name' => 'Issues (Switching Vocals)',
                'album_id' => 1,
                'duration_ms' => 168742,
                'explicit' => 1,
                'popularity' => 20,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1S7KYubk2rQ9d1aydXT9Cd',
                'created_at' => '2025-10-24 21:49:38',
                'updated_at' => '2025-10-24 21:51:17',
            ),
            2 => 
            array (
                'id' => 3,
                'spotify_id' => '36MfYDifxqNRNPJycZVUBs',
            'name' => 'Chained To The Rhythm (Switching Vocals)',
                'album_id' => 1,
                'duration_ms' => 198451,
                'explicit' => 0,
                'popularity' => 23,
                'track_number' => 11,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/36MfYDifxqNRNPJycZVUBs',
                'created_at' => '2025-10-24 21:49:38',
                'updated_at' => '2025-10-24 21:51:17',
            ),
            3 => 
            array (
                'id' => 4,
                'spotify_id' => '4awLraVGZP3nmfh9mJtUTl',
            'name' => 'I Will Follow You Into The Dark (Switching Vocals)',
                'album_id' => 1,
                'duration_ms' => 144112,
                'explicit' => 0,
                'popularity' => 12,
                'track_number' => 12,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4awLraVGZP3nmfh9mJtUTl',
                'created_at' => '2025-10-24 21:49:39',
                'updated_at' => '2025-10-24 21:51:18',
            ),
            4 => 
            array (
                'id' => 5,
                'spotify_id' => '6bM9V66sOJKqaxjdjKalwE',
            'name' => 'I\'m A Mess (Switching Vocals)',
                'album_id' => 2,
                'duration_ms' => 150920,
                'explicit' => 0,
                'popularity' => 40,
                'track_number' => 6,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6bM9V66sOJKqaxjdjKalwE',
                'created_at' => '2025-10-24 21:49:39',
                'updated_at' => '2025-10-24 21:51:18',
            ),
            5 => 
            array (
                'id' => 6,
                'spotify_id' => '4Qd99GGc8yLBCa5AF50MDH',
            'name' => 'Wanted (Switching Vocals)',
                'album_id' => 2,
                'duration_ms' => 164351,
                'explicit' => 0,
                'popularity' => 14,
                'track_number' => 13,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4Qd99GGc8yLBCa5AF50MDH',
                'created_at' => '2025-10-24 21:49:40',
                'updated_at' => '2025-10-24 21:51:19',
            ),
            6 => 
            array (
                'id' => 7,
                'spotify_id' => '3nXM5iwjI3F4sS9u7HIJO7',
                'name' => 'Electric',
                'album_id' => 3,
                'duration_ms' => 163677,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3nXM5iwjI3F4sS9u7HIJO7',
                'created_at' => '2025-10-24 21:49:40',
                'updated_at' => '2025-10-24 21:51:20',
            ),
            7 => 
            array (
                'id' => 8,
                'spotify_id' => '0jFbJH06YhxTBaGVPEQz0V',
                'name' => 'Roquefeller Street',
                'album_id' => 4,
                'duration_ms' => 147121,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/0jFbJH06YhxTBaGVPEQz0V',
                'created_at' => '2025-10-24 21:49:40',
                'updated_at' => '2025-10-24 21:51:20',
            ),
            8 => 
            array (
                'id' => 9,
                'spotify_id' => '6WeKlARKRHB2IQay3aiUw4',
                'name' => 'Around the World - Original Nightcore Edit',
                'album_id' => 5,
                'duration_ms' => 162835,
                'explicit' => 0,
                'popularity' => 35,
                'track_number' => 10,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6WeKlARKRHB2IQay3aiUw4',
                'created_at' => '2025-10-24 21:49:41',
                'updated_at' => '2025-10-24 21:51:20',
            ),
            9 => 
            array (
                'id' => 10,
                'spotify_id' => '1C4yZskyZcc1oMVSQNGErl',
                'name' => 'Anima Libera',
                'album_id' => 6,
                'duration_ms' => 155764,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1C4yZskyZcc1oMVSQNGErl',
                'created_at' => '2025-10-24 21:49:42',
                'updated_at' => '2025-10-24 21:51:21',
            ),
            10 => 
            array (
                'id' => 11,
                'spotify_id' => '4dznfoVwnM9ZJinxMMZsOh',
                'name' => 'This Little Girl',
                'album_id' => 7,
                'duration_ms' => 157874,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4dznfoVwnM9ZJinxMMZsOh',
                'created_at' => '2025-10-24 21:49:42',
                'updated_at' => '2025-10-24 21:51:22',
            ),
            11 => 
            array (
                'id' => 12,
                'spotify_id' => '1tQpGLVs15Te6hxDAsjULB',
                'name' => 'In My Mind',
                'album_id' => 8,
                'duration_ms' => 167451,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1tQpGLVs15Te6hxDAsjULB',
                'created_at' => '2025-10-24 21:49:43',
                'updated_at' => '2025-10-24 21:51:22',
            ),
            12 => 
            array (
                'id' => 13,
                'spotify_id' => '6tEz5BGLZ5f1xKD1LBRMDv',
                'name' => 'Down',
                'album_id' => 9,
                'duration_ms' => 144349,
                'explicit' => 0,
                'popularity' => 17,
                'track_number' => 7,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6tEz5BGLZ5f1xKD1LBRMDv',
                'created_at' => '2025-10-24 21:49:43',
                'updated_at' => '2025-10-24 21:51:23',
            ),
            13 => 
            array (
                'id' => 14,
                'spotify_id' => '35WCpc3Mz2ysTn8aN7kq1h',
            'name' => 'Moonlight Shadow (Full Reloaded 2018) - Radio Edit',
                'album_id' => 10,
                'duration_ms' => 195199,
                'explicit' => 0,
                'popularity' => 25,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/35WCpc3Mz2ysTn8aN7kq1h',
                'created_at' => '2025-10-24 21:49:45',
                'updated_at' => '2025-10-24 21:51:24',
            ),
            14 => 
            array (
                'id' => 15,
                'spotify_id' => '3hnIAUmgpwM2GvZKCHEnTE',
                'name' => 'Animals',
                'album_id' => 11,
                'duration_ms' => 152785,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3hnIAUmgpwM2GvZKCHEnTE',
                'created_at' => '2025-10-24 21:49:45',
                'updated_at' => '2025-10-24 21:51:25',
            ),
            15 => 
            array (
                'id' => 16,
                'spotify_id' => '02ZX6IhNyri8kLwvPt6bnD',
                'name' => 'I Dream',
                'album_id' => 12,
                'duration_ms' => 165328,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/02ZX6IhNyri8kLwvPt6bnD',
                'created_at' => '2025-10-24 21:49:46',
                'updated_at' => '2025-10-24 21:51:25',
            ),
            16 => 
            array (
                'id' => 17,
                'spotify_id' => '5yBGUFRqLjTt9Rrli6w0cx',
            'name' => 'Drag Me Down (Switching Vocals)',
                'album_id' => 13,
                'duration_ms' => 137794,
                'explicit' => 0,
                'popularity' => 29,
                'track_number' => 6,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5yBGUFRqLjTt9Rrli6w0cx',
                'created_at' => '2025-10-24 21:49:46',
                'updated_at' => '2025-10-24 21:51:26',
            ),
            17 => 
            array (
                'id' => 18,
                'spotify_id' => '6VRCyM1kPAd47UJqCiGvPq',
                'name' => 'Rockabye',
                'album_id' => 14,
                'duration_ms' => 154836,
                'explicit' => 0,
                'popularity' => 26,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6VRCyM1kPAd47UJqCiGvPq',
                'created_at' => '2025-10-24 21:49:47',
                'updated_at' => '2025-10-24 21:51:26',
            ),
            18 => 
            array (
                'id' => 19,
                'spotify_id' => '1LR8A1UogM4eVsHqRWbF9I',
                'name' => 'So Am I',
                'album_id' => 15,
                'duration_ms' => 155000,
                'explicit' => 0,
                'popularity' => 37,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1LR8A1UogM4eVsHqRWbF9I',
                'created_at' => '2025-10-24 21:49:47',
                'updated_at' => '2025-10-24 21:51:27',
            ),
            19 => 
            array (
                'id' => 20,
                'spotify_id' => '1LfDaoYwaBzmYM35za0LHB',
            'name' => 'Meet Me on the Battlefield (Svrcina Nightcore Remix)',
                'album_id' => 16,
                'duration_ms' => 219720,
                'explicit' => 0,
                'popularity' => 35,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1LfDaoYwaBzmYM35za0LHB',
                'created_at' => '2025-10-24 21:49:48',
                'updated_at' => '2025-10-24 21:51:27',
            ),
            20 => 
            array (
                'id' => 21,
                'spotify_id' => '5kRBzRZmZTXVg8okC7SJFZ',
                'name' => 'Another Day Of Sun',
                'album_id' => 17,
                'duration_ms' => 228173,
                'explicit' => 0,
                'popularity' => 64,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5kRBzRZmZTXVg8okC7SJFZ',
                'created_at' => '2025-10-24 21:49:49',
                'updated_at' => '2025-10-24 21:51:29',
            ),
            21 => 
            array (
                'id' => 22,
                'spotify_id' => '39ncDMVidHOeQgeC5anYZM',
                'name' => 'Someone In The Crowd',
                'album_id' => 17,
                'duration_ms' => 259613,
                'explicit' => 0,
                'popularity' => 60,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/39ncDMVidHOeQgeC5anYZM',
                'created_at' => '2025-10-24 21:49:50',
                'updated_at' => '2025-10-24 21:51:30',
            ),
            22 => 
            array (
                'id' => 23,
                'spotify_id' => '4r9hiElqKWMPT4Z3vN2exq',
                'name' => 'A Lovely Night',
                'album_id' => 17,
                'duration_ms' => 236506,
                'explicit' => 0,
                'popularity' => 63,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4r9hiElqKWMPT4Z3vN2exq',
                'created_at' => '2025-10-24 21:49:52',
                'updated_at' => '2025-10-24 21:51:31',
            ),
            23 => 
            array (
                'id' => 24,
                'spotify_id' => '0VICzaRdctD8XGfDstBjQY',
                'name' => 'Your Lie in April - Medley',
                'album_id' => 18,
                'duration_ms' => 368767,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/0VICzaRdctD8XGfDstBjQY',
                'created_at' => '2025-10-24 21:49:53',
                'updated_at' => '2025-10-24 21:51:32',
            ),
            24 => 
            array (
                'id' => 25,
                'spotify_id' => '5AMlkhfcb7TEVghsY4ymdD',
                'name' => 'Carnival Kerfuffle',
                'album_id' => 19,
                'duration_ms' => 241053,
                'explicit' => 0,
                'popularity' => 43,
                'track_number' => 21,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5AMlkhfcb7TEVghsY4ymdD',
                'created_at' => '2025-10-24 21:49:53',
                'updated_at' => '2025-10-24 21:51:33',
            ),
            25 => 
            array (
                'id' => 26,
                'spotify_id' => '2nqNDNJtrLeEq8b5Npjd9f',
                'name' => 'Slap That Bass',
                'album_id' => 20,
                'duration_ms' => 311266,
                'explicit' => 0,
                'popularity' => 7,
                'track_number' => 8,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2nqNDNJtrLeEq8b5Npjd9f',
                'created_at' => '2025-10-24 21:49:53',
                'updated_at' => '2025-10-24 21:51:33',
            ),
            26 => 
            array (
                'id' => 27,
                'spotify_id' => '5RABLbc0whf2pVD7ISl3Yt',
                'name' => 'AIN\'T NOTHIN\' LIKE A FUNKY BEAT',
                'album_id' => 21,
                'duration_ms' => 205275,
                'explicit' => 0,
                'popularity' => 48,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5RABLbc0whf2pVD7ISl3Yt',
                'created_at' => '2025-10-24 21:49:55',
                'updated_at' => '2025-10-24 21:51:35',
            ),
            27 => 
            array (
                'id' => 28,
                'spotify_id' => '2ufr0Gs4OWL1Uo22EsJDSx',
                'name' => 'Introduction',
                'album_id' => 19,
                'duration_ms' => 211706,
                'explicit' => 0,
                'popularity' => 41,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2ufr0Gs4OWL1Uo22EsJDSx',
                'created_at' => '2025-10-24 21:49:55',
                'updated_at' => '2025-10-24 21:51:35',
            ),
            28 => 
            array (
                'id' => 29,
                'spotify_id' => '6wpAClCweGJWZWeC8GZ6rW',
                'name' => 'Shall We Dance?',
                'album_id' => 20,
                'duration_ms' => 223626,
                'explicit' => 0,
                'popularity' => 5,
                'track_number' => 5,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6wpAClCweGJWZWeC8GZ6rW',
                'created_at' => '2025-10-24 21:49:56',
                'updated_at' => '2025-10-24 21:51:35',
            ),
            29 => 
            array (
                'id' => 30,
                'spotify_id' => '1Vk4yRsz0iBzDiZEoFMQyv',
                'name' => 'Mia & Sebastian’s Theme',
                'album_id' => 17,
                'duration_ms' => 98040,
                'explicit' => 0,
                'popularity' => 70,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1Vk4yRsz0iBzDiZEoFMQyv',
                'created_at' => '2025-10-24 21:49:58',
                'updated_at' => '2025-10-24 21:51:37',
            ),
            30 => 
            array (
                'id' => 31,
                'spotify_id' => '6YnPqvc66bdYGGOJIlDEz1',
                'name' => 'Battle Against A True Hero',
                'album_id' => 22,
                'duration_ms' => 156800,
                'explicit' => 0,
                'popularity' => 62,
                'track_number' => 98,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6YnPqvc66bdYGGOJIlDEz1',
                'created_at' => '2025-10-24 21:49:58',
                'updated_at' => '2025-10-24 21:51:37',
            ),
            31 => 
            array (
                'id' => 32,
                'spotify_id' => '73GFaOmDNWvQVEFbJN9s4j',
            'name' => 'Coconut Mall (From "Mario Kart Wii")',
                'album_id' => 23,
                'duration_ms' => 240135,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 19,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/73GFaOmDNWvQVEFbJN9s4j',
                'created_at' => '2025-10-24 21:49:59',
                'updated_at' => '2025-10-24 21:51:38',
            ),
            32 => 
            array (
                'id' => 33,
                'spotify_id' => '7uVpjihhrP2plvxnSzP6JY',
                'name' => 'Clip Joint Calamity',
                'album_id' => 19,
                'duration_ms' => 234626,
                'explicit' => 0,
                'popularity' => 38,
                'track_number' => 15,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7uVpjihhrP2plvxnSzP6JY',
                'created_at' => '2025-10-24 21:49:59',
                'updated_at' => '2025-10-24 21:51:38',
            ),
            33 => 
            array (
                'id' => 34,
                'spotify_id' => '583sTGbbnypJxK2ahpd4RD',
            'name' => 'Unravel (From "Tokyo Ghoul")',
                'album_id' => 24,
                'duration_ms' => 235555,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 6,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/583sTGbbnypJxK2ahpd4RD',
                'created_at' => '2025-10-24 21:50:00',
                'updated_at' => '2025-10-24 21:51:39',
            ),
            34 => 
            array (
                'id' => 35,
                'spotify_id' => '1J03Vp93ybKIxfzYI4YJtL',
                'name' => 'MEGALOVANIA',
                'album_id' => 22,
                'duration_ms' => 156000,
                'explicit' => 0,
                'popularity' => 67,
                'track_number' => 100,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1J03Vp93ybKIxfzYI4YJtL',
                'created_at' => '2025-10-24 21:50:00',
                'updated_at' => '2025-10-24 21:51:39',
            ),
            35 => 
            array (
                'id' => 36,
                'spotify_id' => '2C4wrDoJm6DU4nOCejVcTL',
            'name' => 'Mii Channel (From "Nintendo Wii Mii Channel")',
                'album_id' => 25,
                'duration_ms' => 312434,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 16,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2C4wrDoJm6DU4nOCejVcTL',
                'created_at' => '2025-10-24 21:50:01',
                'updated_at' => '2025-10-24 21:51:40',
            ),
            36 => 
            array (
                'id' => 37,
                'spotify_id' => '1cXEPioO38pv5ITT7xkE92',
                'name' => 'Entrance to Nevada',
                'album_id' => 20,
                'duration_ms' => 162840,
                'explicit' => 0,
                'popularity' => 4,
                'track_number' => 6,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1cXEPioO38pv5ITT7xkE92',
                'created_at' => '2025-10-24 21:50:02',
                'updated_at' => '2025-10-24 21:51:41',
            ),
            37 => 
            array (
                'id' => 38,
                'spotify_id' => '7eVPSl96DJOMSc9rIBn6ft',
                'name' => 'Sugarland Shimmy',
                'album_id' => 19,
                'duration_ms' => 221693,
                'explicit' => 0,
                'popularity' => 35,
                'track_number' => 18,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7eVPSl96DJOMSc9rIBn6ft',
                'created_at' => '2025-10-24 21:50:02',
                'updated_at' => '2025-10-24 21:51:41',
            ),
            38 => 
            array (
                'id' => 39,
                'spotify_id' => '53BIF7mH7UL7yTzOsKIoEw',
                'name' => 'Jump Up, Super Star!',
                'album_id' => 26,
                'duration_ms' => 244500,
                'explicit' => 0,
                'popularity' => 30,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/53BIF7mH7UL7yTzOsKIoEw',
                'created_at' => '2025-10-24 21:50:03',
                'updated_at' => '2025-10-24 21:51:41',
            ),
            39 => 
            array (
                'id' => 40,
                'spotify_id' => '5nf9AKMqq3lRp4y1UUW3gR',
            'name' => 'Mor Ardain - Roaming the Wastes (From "Xenoblade Chronicles 2")',
                'album_id' => 23,
                'duration_ms' => 391337,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 20,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5nf9AKMqq3lRp4y1UUW3gR',
                'created_at' => '2025-10-24 21:50:03',
                'updated_at' => '2025-10-24 21:51:42',
            ),
            40 => 
            array (
                'id' => 41,
                'spotify_id' => '0887MdpCLClQkO9vEbPmud',
                'name' => 'Break My Soul',
                'album_id' => 27,
                'duration_ms' => 221675,
                'explicit' => 0,
                'popularity' => 0,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/0887MdpCLClQkO9vEbPmud',
                'created_at' => '2025-10-24 21:50:05',
                'updated_at' => '2025-10-24 21:51:44',
            ),
            41 => 
            array (
                'id' => 42,
                'spotify_id' => '4Az7HG3nJxycTF44rnD1dU',
                'name' => 'Money Walk',
                'album_id' => 28,
                'duration_ms' => 133491,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4Az7HG3nJxycTF44rnD1dU',
                'created_at' => '2025-10-24 21:50:06',
                'updated_at' => '2025-10-24 21:52:08',
            ),
            42 => 
            array (
                'id' => 43,
                'spotify_id' => '1kxdYK4gpxjrlqOckWLFMT',
            'name' => 'Lil Mama (feat. Renni Rucci)',
                'album_id' => 29,
                'duration_ms' => 120413,
                'explicit' => 1,
                'popularity' => 13,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1kxdYK4gpxjrlqOckWLFMT',
                'created_at' => '2025-10-24 21:50:07',
                'updated_at' => '2025-10-24 21:52:01',
            ),
            43 => 
            array (
                'id' => 44,
                'spotify_id' => '12aSfxXuZcfe6dw1uysybf',
                'name' => 'Watch Me',
                'album_id' => 30,
                'duration_ms' => 86693,
                'explicit' => 1,
                'popularity' => 3,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/12aSfxXuZcfe6dw1uysybf',
                'created_at' => '2025-10-24 21:50:08',
                'updated_at' => '2025-10-24 21:52:00',
            ),
            44 => 
            array (
                'id' => 45,
                'spotify_id' => '5MC0H1PFIT9KFfkGj5SGgk',
                'name' => 'Water',
                'album_id' => 31,
                'duration_ms' => 149211,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5MC0H1PFIT9KFfkGj5SGgk',
                'created_at' => '2025-10-24 21:50:09',
                'updated_at' => '2025-10-24 21:52:00',
            ),
            45 => 
            array (
                'id' => 46,
                'spotify_id' => '7oxy6gcerLrJ83E1dynA7W',
                'name' => 'Just Woke Up',
                'album_id' => 32,
                'duration_ms' => 111588,
                'explicit' => 1,
                'popularity' => 35,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7oxy6gcerLrJ83E1dynA7W',
                'created_at' => '2025-10-24 21:50:10',
                'updated_at' => '2025-10-24 21:52:02',
            ),
            46 => 
            array (
                'id' => 47,
                'spotify_id' => '2FksCnG0E820fip2thOd27',
                'name' => 'Don\'t Like Me',
                'album_id' => 33,
                'duration_ms' => 153941,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2FksCnG0E820fip2thOd27',
                'created_at' => '2025-10-24 21:50:11',
                'updated_at' => '2025-10-24 21:52:09',
            ),
            47 => 
            array (
                'id' => 48,
                'spotify_id' => '2ABMrhgEWfTFUKjkwVjscn',
                'name' => 'Pull up Boosie',
                'album_id' => 34,
                'duration_ms' => 192071,
                'explicit' => 1,
                'popularity' => 11,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2ABMrhgEWfTFUKjkwVjscn',
                'created_at' => '2025-10-24 21:50:11',
                'updated_at' => '2025-10-24 21:52:04',
            ),
            48 => 
            array (
                'id' => 49,
                'spotify_id' => '0JFc7Gspd8BKw5bAUPXNFH',
                'name' => 'Can\'t Clone Me',
                'album_id' => 35,
                'duration_ms' => 136483,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/0JFc7Gspd8BKw5bAUPXNFH',
                'created_at' => '2025-10-24 21:50:12',
                'updated_at' => '2025-10-24 21:52:04',
            ),
            49 => 
            array (
                'id' => 50,
                'spotify_id' => '7Csx5Gsp3ouNLVDjbJ6Apl',
                'name' => 'KILLIN SHIT/ SAIYAN PRIDE',
                'album_id' => 36,
                'duration_ms' => 230890,
                'explicit' => 1,
                'popularity' => 11,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7Csx5Gsp3ouNLVDjbJ6Apl',
                'created_at' => '2025-10-24 21:50:13',
                'updated_at' => '2025-10-24 21:52:03',
            ),
            50 => 
            array (
                'id' => 51,
                'spotify_id' => '2gwkD6igEhQbDQegRCcdoB',
                'name' => 'Suge',
                'album_id' => 37,
                'duration_ms' => 163320,
                'explicit' => 1,
                'popularity' => 67,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2gwkD6igEhQbDQegRCcdoB',
                'created_at' => '2025-10-24 21:50:13',
                'updated_at' => '2025-10-24 21:51:50',
            ),
            51 => 
            array (
                'id' => 52,
                'spotify_id' => '1gH57UHCNuyLWmUiTy3zpM',
                'name' => 'Baby Joker',
                'album_id' => 38,
                'duration_ms' => 158640,
                'explicit' => 1,
                'popularity' => 25,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1gH57UHCNuyLWmUiTy3zpM',
                'created_at' => '2025-10-24 21:50:14',
                'updated_at' => '2025-10-24 21:51:51',
            ),
            52 => 
            array (
                'id' => 53,
                'spotify_id' => '4ak7xjvBeBOcJGWFDX9w5n',
                'name' => 'Rodeo',
                'album_id' => 39,
                'duration_ms' => 158706,
                'explicit' => 1,
                'popularity' => 61,
                'track_number' => 5,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4ak7xjvBeBOcJGWFDX9w5n',
                'created_at' => '2025-10-24 21:50:14',
                'updated_at' => '2025-10-24 21:51:52',
            ),
            53 => 
            array (
                'id' => 54,
                'spotify_id' => '5ry2OE6R2zPQFDO85XkgRb',
            'name' => 'Money In The Grave (Drake ft. Rick Ross)',
                'album_id' => 40,
                'duration_ms' => 205426,
                'explicit' => 1,
                'popularity' => 73,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5ry2OE6R2zPQFDO85XkgRb',
                'created_at' => '2025-10-24 21:50:15',
                'updated_at' => '2025-10-24 21:51:53',
            ),
            54 => 
            array (
                'id' => 55,
                'spotify_id' => '1kBbgxAUc4HQv7cgIayIDH',
                'name' => 'Ransom',
                'album_id' => 41,
                'duration_ms' => 131280,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1kBbgxAUc4HQv7cgIayIDH',
                'created_at' => '2025-10-24 21:50:16',
                'updated_at' => '2025-10-24 21:51:53',
            ),
            55 => 
            array (
                'id' => 56,
                'spotify_id' => '7DcvwMAiqKJQD1rrdfxSDx',
            'name' => 'The London (feat. J. Cole & Travis Scott)',
                'album_id' => 42,
                'duration_ms' => 200106,
                'explicit' => 1,
                'popularity' => 62,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7DcvwMAiqKJQD1rrdfxSDx',
                'created_at' => '2025-10-24 21:50:17',
                'updated_at' => '2025-10-24 21:51:54',
            ),
            56 => 
            array (
                'id' => 57,
                'spotify_id' => '6uFn47ACjqYkc0jADwEdj1',
            'name' => 'Pop Out (feat. Lil Tjay)',
                'album_id' => 43,
                'duration_ms' => 166560,
                'explicit' => 1,
                'popularity' => 74,
                'track_number' => 5,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6uFn47ACjqYkc0jADwEdj1',
                'created_at' => '2025-10-24 21:50:18',
                'updated_at' => '2025-10-24 21:51:55',
            ),
            57 => 
            array (
                'id' => 58,
                'spotify_id' => '2zjGJ0dChMR0KxBZS15aqo',
            'name' => 'Baguettes in the Face (feat. NAV, Playboi Carti & A Boogie Wit da Hoodie)',
                'album_id' => 44,
                'duration_ms' => 174100,
                'explicit' => 1,
                'popularity' => 62,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/2zjGJ0dChMR0KxBZS15aqo',
                'created_at' => '2025-10-24 21:50:19',
                'updated_at' => '2025-10-24 21:51:56',
            ),
            58 => 
            array (
                'id' => 59,
                'spotify_id' => '3XiNC94b4Tq1xwv70sQJGN',
                'name' => 'Sanguine Paradise',
                'album_id' => 45,
                'duration_ms' => 243976,
                'explicit' => 1,
                'popularity' => 71,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3XiNC94b4Tq1xwv70sQJGN',
                'created_at' => '2025-10-24 21:50:20',
                'updated_at' => '2025-10-24 21:52:09',
            ),
            59 => 
            array (
                'id' => 60,
                'spotify_id' => '3pZO6GoVPeSYDxxsH6vCdj',
            'name' => 'Sunset (with J. Cole feat. Young Nudy)',
                'album_id' => 46,
                'duration_ms' => 178373,
                'explicit' => 1,
                'popularity' => 50,
                'track_number' => 14,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3pZO6GoVPeSYDxxsH6vCdj',
                'created_at' => '2025-10-24 21:50:21',
                'updated_at' => '2025-10-24 21:51:58',
            ),
            60 => 
            array (
                'id' => 61,
                'spotify_id' => '1nDOeWBfRKA5YNQ8bKWzMM',
                'name' => 'head first',
                'album_id' => 47,
                'duration_ms' => 154960,
                'explicit' => 0,
                'popularity' => 51,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/1nDOeWBfRKA5YNQ8bKWzMM',
                'created_at' => '2025-10-24 21:50:23',
                'updated_at' => '2025-10-24 21:51:59',
            ),
            61 => 
            array (
                'id' => 62,
                'spotify_id' => '3eekarcy7kvN4yt5ZFzltW',
                'name' => 'HIGHEST IN THE ROOM',
                'album_id' => 48,
                'duration_ms' => 175720,
                'explicit' => 1,
                'popularity' => 83,
                'track_number' => 1,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3eekarcy7kvN4yt5ZFzltW',
                'created_at' => '2025-10-24 21:50:26',
                'updated_at' => '2025-10-24 21:52:02',
            ),
            62 => 
            array (
                'id' => 63,
                'spotify_id' => '0fySG6A6qLE8IvDpayb5bM',
                'name' => 'VIBEZ',
                'album_id' => 49,
                'duration_ms' => 144935,
                'explicit' => 1,
                'popularity' => 64,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/0fySG6A6qLE8IvDpayb5bM',
                'created_at' => '2025-10-24 21:50:29',
                'updated_at' => '2025-10-24 21:52:05',
            ),
            63 => 
            array (
                'id' => 64,
                'spotify_id' => '7cyeGclH71MayOuQ7qtLFl',
                'name' => 'BIG',
                'album_id' => 50,
                'duration_ms' => 225919,
                'explicit' => 1,
                'popularity' => 61,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/7cyeGclH71MayOuQ7qtLFl',
                'created_at' => '2025-10-24 21:50:29',
                'updated_at' => '2025-10-24 21:52:05',
            ),
            64 => 
            array (
                'id' => 65,
                'spotify_id' => '6UFEJuDXQMWhL5UH5f9fUR',
            'name' => 'Enemies (feat. DaBaby)',
                'album_id' => 51,
                'duration_ms' => 196760,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 3,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/6UFEJuDXQMWhL5UH5f9fUR',
                'created_at' => '2025-10-24 21:50:30',
                'updated_at' => '2025-10-24 21:52:06',
            ),
            65 => 
            array (
                'id' => 66,
                'spotify_id' => '5CMUThHlepHR8c1xD0QYzs',
                'name' => 'They Afraid Of You',
                'album_id' => 52,
                'duration_ms' => 138469,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 5,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/5CMUThHlepHR8c1xD0QYzs',
                'created_at' => '2025-10-24 21:50:31',
                'updated_at' => '2025-10-24 21:52:06',
            ),
            66 => 
            array (
                'id' => 67,
                'spotify_id' => '75T8ffHTOQHyzwoSwXHbyX',
                'name' => 'Fuck That',
                'album_id' => 53,
                'duration_ms' => 155950,
                'explicit' => 1,
                'popularity' => 0,
                'track_number' => 4,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/75T8ffHTOQHyzwoSwXHbyX',
                'created_at' => '2025-10-24 21:50:31',
                'updated_at' => '2025-10-24 21:52:07',
            ),
            67 => 
            array (
                'id' => 68,
                'spotify_id' => '3JZ23tAD3kFjFHtXnzvDKm',
            'name' => 'I Remember (feat. Lil Baby)',
                'album_id' => 54,
                'duration_ms' => 230042,
                'explicit' => 1,
                'popularity' => 53,
                'track_number' => 5,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/3JZ23tAD3kFjFHtXnzvDKm',
                'created_at' => '2025-10-24 21:50:32',
                'updated_at' => '2025-10-24 21:52:08',
            ),
            68 => 
            array (
                'id' => 69,
                'spotify_id' => '78k2sWMlmtICqojUaTgk9J',
                'name' => 'Kiccin Shit',
                'album_id' => 55,
                'duration_ms' => 170782,
                'explicit' => 1,
                'popularity' => 40,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/78k2sWMlmtICqojUaTgk9J',
                'created_at' => '2025-10-24 21:50:34',
                'updated_at' => '2025-10-24 21:52:10',
            ),
            69 => 
            array (
                'id' => 70,
                'spotify_id' => '4dqkKnzOJ3fWduqKcHi374',
            'name' => 'Virtual (Blue Balenciagas)',
                'album_id' => 56,
                'duration_ms' => 193618,
                'explicit' => 1,
                'popularity' => 65,
                'track_number' => 2,
                'preview_url' => NULL,
                'external_url' => 'https://open.spotify.com/track/4dqkKnzOJ3fWduqKcHi374',
                'created_at' => '2025-10-24 21:50:35',
                'updated_at' => '2025-10-24 21:52:10',
            ),
        ));
        
        
    }
}