<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArtistTrackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --mode=table --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'artist_id' => 1,
                'track_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 2,
                'artist_id' => 1,
                'track_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 3,
                'artist_id' => 1,
                'track_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 4,
                'artist_id' => 1,
                'track_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 5,
                'artist_id' => 1,
                'track_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 6,
                'artist_id' => 1,
                'track_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 7,
                'artist_id' => 2,
                'track_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 8,
                'artist_id' => 3,
                'track_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 9,
                'artist_id' => 5,
                'track_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 10,
                'artist_id' => 6,
                'track_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 11,
                'artist_id' => 7,
                'track_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 12,
                'artist_id' => 7,
                'track_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 13,
                'artist_id' => 8,
                'track_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 14,
                'artist_id' => 9,
                'track_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 15,
                'artist_id' => 1,
                'track_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 16,
                'artist_id' => 10,
                'track_id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 17,
                'artist_id' => 9,
                'track_id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 18,
                'artist_id' => 8,
                'track_id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 19,
                'artist_id' => 2,
                'track_id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 20,
                'artist_id' => 1,
                'track_id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 21,
                'artist_id' => 11,
                'track_id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 22,
                'artist_id' => 12,
                'track_id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 23,
                'artist_id' => 13,
                'track_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 24,
                'artist_id' => 17,
                'track_id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 25,
                'artist_id' => 18,
                'track_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 26,
                'artist_id' => 19,
                'track_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 27,
                'artist_id' => 20,
                'track_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 28,
                'artist_id' => 21,
                'track_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 29,
                'artist_id' => 22,
                'track_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 30,
                'artist_id' => 18,
                'track_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 31,
                'artist_id' => 23,
                'track_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 32,
                'artist_id' => 24,
                'track_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 33,
                'artist_id' => 26,
                'track_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 34,
                'artist_id' => 27,
                'track_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 35,
                'artist_id' => 28,
                'track_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 36,
                'artist_id' => 29,
                'track_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 37,
                'artist_id' => 30,
                'track_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 38,
                'artist_id' => 31,
                'track_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 39,
                'artist_id' => 24,
                'track_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 40,
                'artist_id' => 26,
                'track_id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 41,
                'artist_id' => 14,
                'track_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 42,
                'artist_id' => 32,
                'track_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 43,
                'artist_id' => 33,
                'track_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 44,
                'artist_id' => 24,
                'track_id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 45,
                'artist_id' => 23,
                'track_id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 46,
                'artist_id' => 32,
                'track_id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 47,
                'artist_id' => 33,
                'track_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 48,
                'artist_id' => 34,
                'track_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 49,
                'artist_id' => 35,
                'track_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 50,
                'artist_id' => 30,
                'track_id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 51,
                'artist_id' => 24,
                'track_id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 52,
                'artist_id' => 36,
                'track_id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 53,
                'artist_id' => 37,
                'track_id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 54,
                'artist_id' => 33,
                'track_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 55,
                'artist_id' => 38,
                'track_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 56,
                'artist_id' => 39,
                'track_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 57,
                'artist_id' => 40,
                'track_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 58,
                'artist_id' => 41,
                'track_id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 59,
                'artist_id' => 42,
                'track_id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 60,
                'artist_id' => 43,
                'track_id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 61,
                'artist_id' => 44,
                'track_id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 62,
                'artist_id' => 45,
                'track_id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 63,
                'artist_id' => 46,
                'track_id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 64,
                'artist_id' => 47,
                'track_id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 65,
                'artist_id' => 48,
                'track_id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 66,
                'artist_id' => 49,
                'track_id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 67,
                'artist_id' => 50,
                'track_id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 68,
                'artist_id' => 51,
                'track_id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 69,
                'artist_id' => 52,
                'track_id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 70,
                'artist_id' => 53,
                'track_id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 71,
                'artist_id' => 54,
                'track_id' => 49,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 72,
                'artist_id' => 55,
                'track_id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 73,
                'artist_id' => 56,
                'track_id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 74,
                'artist_id' => 57,
                'track_id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 75,
                'artist_id' => 58,
                'track_id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 76,
                'artist_id' => 59,
                'track_id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 77,
                'artist_id' => 60,
                'track_id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 78,
                'artist_id' => 61,
                'track_id' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 79,
                'artist_id' => 62,
                'track_id' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 80,
                'artist_id' => 63,
                'track_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 81,
                'artist_id' => 64,
                'track_id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 82,
                'artist_id' => 65,
                'track_id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 83,
                'artist_id' => 66,
                'track_id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 84,
                'artist_id' => 67,
                'track_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 85,
                'artist_id' => 68,
                'track_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 86,
                'artist_id' => 69,
                'track_id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 87,
                'artist_id' => 70,
                'track_id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 88,
                'artist_id' => 71,
                'track_id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 89,
                'artist_id' => 72,
                'track_id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 90,
                'artist_id' => 73,
                'track_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 91,
                'artist_id' => 74,
                'track_id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 92,
                'artist_id' => 65,
                'track_id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 93,
                'artist_id' => 75,
                'track_id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 94,
                'artist_id' => 76,
                'track_id' => 61,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 95,
                'artist_id' => 66,
                'track_id' => 62,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 96,
                'artist_id' => 56,
                'track_id' => 63,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 97,
                'artist_id' => 77,
                'track_id' => 64,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 98,
                'artist_id' => 78,
                'track_id' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 99,
                'artist_id' => 56,
                'track_id' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 100,
                'artist_id' => 79,
                'track_id' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 101,
                'artist_id' => 71,
                'track_id' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 102,
                'artist_id' => 80,
                'track_id' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 103,
                'artist_id' => 81,
                'track_id' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 104,
                'artist_id' => 82,
                'track_id' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 105,
                'artist_id' => 81,
                'track_id' => 69,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 106,
                'artist_id' => 50,
                'track_id' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ]
        ];
        
        DB::table("artist_track")->insert($dataTables);
    }
}